### ISSUE TITLE
About feature extraction.

### ISSUE THREAD

**Issue by EdenGabriel** [yeliudev/R2-Tuning#10]
Hi, guys, thanks for your interesting work.
I have an question about extract_feat.py.

When I use "ViT-B / 32" to extract visual features, the result is 768 dimensions, but text features are 512 dimensions. Is this normal?
BTW, I remember that "ViT-B / 32" corresponds to 512 dimensions. 

Thanks.

**Comment by yeliudev** [comment]
Yes this is normal. According to the CLIP's [paper](https://arxiv.org/pdf/2103.00020), dimensions for vision and language branches are 768 and 512, respectively.

<img width="577" src="https://github.com/user-attachments/assets/4158e281-56d8-47c2-9c42-8259f399b66a">

**Comment by EdenGabriel** [comment]
oops, i see. 
Thanks for your reply.
