### ISSUE TITLE
get killed when runing video more than 40min

### ISSUE THREAD

**Issue by YQYI** [yeliudev/R2-Tuning#13]
I try to get highlight result from video more than 40min in V100，but get killed，looks like something wrong with decord.VideoReader

**Comment by yeliudev** [comment]
Sounds like a problem from the decord. Are you able to run the demo with other video readers, e.g., opencv? Note that our models were trained on relatively short videos (mostly less than 3 minutes), the performance on long videos is not expected to be good. Trimming the video into short chunks would be a better choice.

**Comment by YQYI** [comment]
> Sounds like a problem from the decord. Are you able to run the demo with other video readers, e.g., opencv? Note that our models were trained on relatively short videos (mostly less than 3 minutes), the performance on long videos is not expected to be good. Trimming the video into short chunks would be a better choice.

> I resize the video before run r2-tuning, it works for me
