### ISSUE TITLE
ValueError: Input contains NaN.

### ISSUE THREAD

**Issue by Hserko** [yeliudev/R2-Tuning#16]
Hi, I use a single RTX 3090 to run the code, and I got the error same as title.
![1726496368953](https://github.com/user-attachments/assets/7a19be74-8346-4d55-a4b8-a7d087ddfa54)

**Comment by yeliudev** [comment]
Hi! You may try to disable FP16 by adding `--amp none` when running.

**Comment by Hserko** [comment]
> Hi! You may try to disable FP16 by adding `--amp none` when running.
 Thanks for your help.
