### ISSUE TITLE
About Fig.8 visualization.

### ISSUE THREAD

**Issue by EdenGabriel** [yeliudev/R2-Tuning#17]
Hi guys,
Your insights are enlightening. And thanks for your repo.
I want to understand more about the visualization details in Fig. 8, such as how it was implemented. (After Equation 5, each frame feature is corresponding to 1xC, so, i can not understand how to visual it on an image) If possible, could you please consider open-sourcing the visualization code? Thanks.

**Comment by yeliudev** [comment]
Hi @EdenGabriel, thanks for your interest in our work. We visualize Fig. 8 by plotting the attention map between the query and frame patches, i.e., the `a` after Eq. (4). You can implement it by selecting a frame from `att` after [this line](https://github.com/yeliudev/R2-Tuning/blob/03fbcf68b82e0d72a572b2a33f7f0f603681dcd1/models/adapter.py#L85).

**Comment by EdenGabriel** [comment]
I see.
Thanks.



---- Replied Message ----
| From | Ye ***@***.***> |
| Date | 09/22/2024 21:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [yeliudev/R2-Tuning] About Fig.8 visualization. (Issue #17) |

Hi @EdenGabriel, thanks for your interest in our work. We visualize Fig. 8 by plotting the attention map between the query and frame patches, i.e., the a after Eq. (4). You can implement it by selecting a frame from att after this line.
