### ISSUE TITLE
Question about the calculation of peak GPU memory 

### ISSUE THREAD

**Issue by HenryHZY** [yeliudev/R2-Tuning#19]
Hi, I would like to ask a question about the calculation of peak GPU memory.

As shown in the paper's Table 9, the peak GPU memory (224 × 224 inputs with 32 batch size & FP16) of R2-Tuning is 10.6GB.

While in the provided training log of qvhighlights, the memory is "memory: 28746" using:
```python
# nncore
mem = torch.cuda.max_memory_allocated()
mem_mb = torch.IntTensor([int(mem / (1024 * 1024))]).cuda()
'memory: {}'.format(mem_mb.item())
```

How can we obtain the result in the Table 9? Thank you!

**Comment by yeliudev** [comment]
Hi @HenryHZY! The memory in the training log was calculated from `bs=128`. You may run the model again with `bs=32` to align the results in Table 9.
