### ISSUE TITLE
fp16 training problem

### ISSUE THREAD

**Issue by wenjiajia123** [yeliudev/R2-Tuning#3]
thanks for your projects! when I reimplement this project, I occur the follow problem: `  File "/mnt/bn/experience0313/gengwenjia/R2-Tuning/models/adapter.py", line 72, in forward
    v_emb = self.video_map(video_emb[i])  # B * T * P * C.  RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`. And I checked all dependencies' version, do you know the possible reasons?

**Comment by whyiswmm** [comment]
thanks for your projects! Can you provide some code for readers to run a demo? Input the video and query, output the results, so that we can more intuitively see how advanced your method is.

**Comment by yeliudev** [comment]
Hi @wenjiajia123! Thanks for reporting this problem. It is weird as it did not happen in our environment. Could you please double-check that the code is running on GPU instead of CPU? If the problem still exists, changing back to FP32 (by setting `amp=None` at [here](https://github.com/yeliudev/R2-Tuning/blob/78d5f921b8c854586bb4e12eb0b2ddf3c3389581/tools/launch.py#L87)) should work.

**Comment by wenjiajia123** [comment]
Thank a lot for your reply, it worked!

**Comment by wenjiajia123** [comment]
I just check the log file, and I only modify the amp parameter, it's a little weird. 😂

**Comment by yeliudev** [comment]
Is it possibly caused by slow I/O? You may compare the `data_time` (time spent for data loading & pre-processing in seconds) at each step with our log.

**Comment by wenjiajia123** [comment]
<img width="847" alt="截屏2024-05-16 19 58 53" src="https://github.com/yeliudev/R2-Tuning/assets/114286226/6e87e3f9-bc85-440b-a2b0-c63a76a5280b">
this is my log file, it seems both time is much longer.

**Comment by yeliudev** [comment]
TBH, I currently have no idea about this. It seems more like an issue from the environment rather than the code (though you have confirmed that the dependencies are correct...). We'll see if there are other users mentioning this problem.

**Comment by yeliudev** [comment]
Again, please make sure the code is running on GPU. 😂

**Comment by wenjiajia123** [comment]
thanks for your reply, I wonder what's the total running time without using fp16? could it be the mian reason?🤔️

**Comment by yeliudev** [comment]
We've tested FP32 training and it costs about three and a half hours.

**Comment by wenjiajia123** [comment]
hi, I have fixed the problem through reinstall torch because my cuda version is 11.4. but the data time costs much longer, do you know how to solve it? 😊
<img width="552" alt="截屏2024-05-21 15 50 21" src="https://github.com/yeliudev/R2-Tuning/assets/114286226/8e86f5c0-32fa-4744-9ad0-05cd263ce595">

**Comment by yeliudev** [comment]
This is only for the first few steps. It would be faster after the warmup.
