### ISSUE TITLE
Demo Code

### ISSUE THREAD

**Issue by ghost** [yeliudev/R2-Tuning#4]
Thank you for your projects! Could you provide some code for readers to run a demo? By inputting a video and a query, the output results will allow us to intuitively see the advanced capabilities of your method.

**Comment by yeliudev** [comment]
Hi @whyiswmm! Thanks for your suggestion. We will add the demo code soon.

**Comment by yeliudev** [comment]
We've added the demo code to the repo. Thanks for your waiting!
