### ISSUE TITLE
TypeError: list indices must be integers or slices, not torch.device

### ISSUE THREAD

**Issue by TensorsSun** [yeliudev/R2-Tuning#5]
Hi, I use a single RTX 3090 to run the code, and I got the error same as title.
![1717174866789](https://github.com/yeliudev/R2-Tuning/assets/48124968/85227a36-a44f-4de0-8830-c99fa52a6a7e)
And I see similar questions on these two pages:
https://github.com/open-mmlab/mmdetection/issues/4538
https://github.com/open-mmlab/mmocr/issues/92
Could you help me with this problem？Thanks

**Comment by yeliudev** [comment]
Could you please provide the Python version and the list of pip packages (and versions) you are using?

**Comment by TensorsSun** [comment]
Sure, the Python version is 3.10.14, and the pip packages are:
![1717184526261](https://github.com/yeliudev/R2-Tuning/assets/48124968/bc887bc0-936c-4185-b1b6-11e62b260a86)

**Comment by yeliudev** [comment]
We were using `torch==2.2.1` instead of `1.13.0`. Could you please align the PyTorch & Torchvision versions and try again?

**Comment by TensorsSun** [comment]
I tried torch==2.2.1 before, but I met the same problem in https://github.com/yeliudev/R2-Tuning/issues/3#issuecomment-2115051845: the time is much longer about 10 days.

**Comment by yeliudev** [comment]
Are other versions with `torch>=2.1` working? The scatter function here should work with at least 2.1.

**Comment by TensorsSun** [comment]
I rechecked my environment and found that the code can run normally when `torch==2.2.1`. The previous exception was caused by slow I/O. Thanks for your help.

**Comment by yeliudev** [comment]
Good to know that. Thanks for reporting!
