### ISSUE TITLE
Learnable gates

### ISSUE THREAD

**Issue by pangzss** [yeliudev/R2-Tuning#6]
Thank you for sharing such impressive work and the well-organized codebase!

Due to my lack of experience in this area, I am wondering what is the role of the learnable gates in Eq. (6) and Eq. (7). I tried to find ablation studies in this respect but failed to find any in the paper.

I would greatly appreciate it if you could share your insight into designing the learnable gates or links to previous works that have initiated the use of them.

Thank you.

**Comment by yeliudev** [comment]
Thanks for your interest in our work! The learnable gates are more like implementation tricks to stabilize training (when performing feature fusion from difference sources) - at the very beginning of training, the model would start from $e_{pool}^n = e_v^{n,0}$ when $e_{token}^n$ is not well-extracted (Eq. 6), and set $\hat{h}^{k-1} = 0.5 \cdot e_{pool}^n + 0.5 \cdot h^{k-1}$ as an initialization (Eq. 7). The activation functions on $g^k$ and $\phi^k$ are used to restrict their ranges.

You can try the ablations by modifying [here](https://github.com/yeliudev/R2-Tuning/blob/78d5f921b8c854586bb4e12eb0b2ddf3c3389581/models/adapter.py#L89) and [here](https://github.com/yeliudev/R2-Tuning/blob/78d5f921b8c854586bb4e12eb0b2ddf3c3389581/models/adapter.py#L94).
