### ISSUE TITLE
WARNING: The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by ffiioonnaa** [yeliudev/R2-Tuning#7]
Hi,thanks for your work.
I got this warning when i run inference.py, Is this warning normal？
WARNING: The model and loaded state dict do not match exactly

Missing keys in source state dict: clip.positional_embedding, clip.text_projection, clip.logit_scale, clip.visual.class_embedding, clip.visual.positional_embedding, clip.visual.proj, clip.visual.conv1.weight, clip.visual.ln_pre.weight, clip.visual.ln_pre.bias, clip.visual.transformer.resblocks.0.attn.in_proj_weight, clip.visual.transformer.resblocks.0.attn.in_proj_bias, clip.visual.transformer.resblocks.0.attn.out_proj.weight, clip.visual.transformer.resblocks.0.attn.out_proj.bias, clip.visual.transformer.resblocks.0.ln_1.weight, clip.visual.transformer.resblocks.0.ln_1.bias, clip.visual.transformer.resblocks.0.mlp.c_fc.weight, clip.visual.transformer.resblocks.0.mlp.c_fc.bias, clip.visual.transformer.resblocks.0.mlp.c_proj.weight, clip.visual.transformer.resblocks.0.mlp.c_proj.bias, clip.visual.transformer.resblocks.0.ln_2.weight, clip.visual.transformer.resblocks.0.ln_2.bias, clip.visual.transformer.resblocks.1.attn.in_proj_weight, clip.visual.transformer.resblocks.1.attn.in_proj_bias, clip.visual.transformer.resblocks.1.attn.out_proj.weight, clip.visual.transformer.resblocks.1.attn.out_proj.bias, clip.visual.transformer.resblocks.1.ln_1.weight, clip.visual.transformer.resblocks.1.ln_1.bias, clip.visual.transformer.resblocks.1.mlp.c_fc.weight, clip.visual.transformer.resblocks.1.mlp.c_fc.bias, clip.visual.transformer.resblocks.1.mlp.c_proj.weight, clip.visual.transformer.resblocks.1.mlp.c_proj.bias, clip.visual.transformer.resblocks.1.ln_2.weight, clip.visual.transformer.resblocks.1.ln_2.bias, clip.visual.transformer.resblocks.2.attn.in_proj_weight, clip.visual.transformer.resblocks.2.attn.in_proj_bias, clip.visual.transformer.resblocks.2.attn.out_proj.weight, clip.visual.transformer.resblocks.2.attn.out_proj.bias, clip.visual.transformer.resblocks.2.ln_1.weight, clip.visual.transformer.resblocks.2.ln_1.bias, clip.visual.transformer.resblocks.2.mlp.c_fc.weight, clip.visual.transformer.resblocks.2.mlp.c_fc.bias, clip.visual.transformer.resblocks.2.mlp.c_proj.weight, clip.visual.transformer.resblocks.2.mlp.c_proj.bias, clip.visual.transformer.resblocks.2.ln_2.weight, clip.visual.transformer.resblocks.2.ln_2.bias, clip.visual.transformer.resblocks.3.attn.in_proj_weight, clip.visual.transformer.resblocks.3.attn.in_proj_bias, clip.visual.transformer.resblocks.3.attn.out_proj.weight, clip.visual.transformer.resblocks.3.attn.out_proj.bias, clip.visual.transformer.resblocks.3.ln_1.weight, clip.visual.transformer.resblocks.3.ln_1.bias, clip.visual.transformer.resblocks.3.mlp.c_fc.weight, clip.visual.transformer.resblocks.3.mlp.c_fc.bias, clip.visual.transformer.resblocks.3.mlp.c_proj.weight, clip.visual.transformer.resblocks.3.mlp.c_proj.bias, clip.visual.transformer.resblocks.3.ln_2.weight, clip.visual.transformer.resblocks.3.ln_2.bias, clip.visual.transformer.resblocks.4.attn.in_proj_weight, clip.visual.transformer.resblocks.4.attn.in_proj_bias, clip.visual.transformer.resblocks.4.attn.out_proj.weight, clip.visual.transformer.resblocks.4.attn.out_proj.bias, clip.visual.transformer.resblocks.4.ln_1.weight, clip.visual.transformer.resblocks.4.ln_1.bias, clip.visual.transformer.resblocks.4.mlp.c_fc.weight, clip.visual.transformer.resblocks.4.mlp.c_fc.bias, clip.visual.transformer.resblocks.4.mlp.c_proj.weight, clip.visual.transformer.resblocks.4.mlp.c_proj.bias, clip.visual.transformer.resblocks.4.ln_2.weight, clip.visual.transformer.resblocks.4.ln_2.bias, clip.visual.transformer.resblocks.5.attn.in_proj_weight, clip.visual.transformer.resblocks.5.attn.in_proj_bias, clip.visual.transformer.resblocks.5.attn.out_proj.weight, clip.visual.transformer.resblocks.5.attn.out_proj.bias, clip.visual.transformer.resblocks.5.ln_1.weight, clip.visual.transformer.resblocks.5.ln_1.bias, clip.visual.transformer.resblocks.5.mlp.c_fc.weight, clip.visual.transformer.resblocks.5.mlp.c_fc.bias, clip.visual.transformer.resblocks.5.mlp.c_proj.weight, clip.visual.transformer.resblocks.5.mlp.c_proj.bias, clip.visual.transformer.resblocks.5.ln_2.weight, clip.visual.transformer.resblocks.5.ln_2.bias, clip.visual.transformer.resblocks.6.attn.in_proj_weight, clip.visual.transformer.resblocks.6.attn.in_proj_bias, clip.visual.transformer.resblocks.6.attn.out_proj.weight, clip.visual.transformer.resblocks.6.attn.out_proj.bias, clip.visual.transformer.resblocks.6.ln_1.weight, clip.visual.transformer.resblocks.6.ln_1.bias, clip.visual.transformer.resblocks.6.mlp.c_fc.weight, clip.visual.transformer.resblocks.6.mlp.c_fc.bias, clip.visual.transformer.resblocks.6.mlp.c_proj.weight, clip.visual.transformer.resblocks.6.mlp.c_proj.bias, clip.visual.transformer.resblocks.6.ln_2.weight, clip.visual.transformer.resblocks.6.ln_2.bias, clip.visual.transformer.resblocks.7.attn.in_proj_weight, clip.visual.transformer.resblocks.7.attn.in_proj_bias, clip.visual.transformer.resblocks.7.attn.out_proj.weight, clip.visual.transformer.resblocks.7.attn.out_proj.bias, clip.visual.transformer.resblocks.7.ln_1.weight, clip.visual.transformer.resblocks.7.ln_1.bias, clip.visual.transformer.resblocks.7.mlp.c_fc.weight, clip.visual.transformer.resblocks.7.mlp.c_fc.bias, clip.visual.transformer.resblocks.7.mlp.c_proj.weight, clip.visual.transformer.resblocks.7.mlp.c_proj.bias, clip.visual.transformer.resblocks.7.ln_2.weight, clip.visual.transformer.resblocks.7.ln_2.bias, clip.visual.transformer.resblocks.8.attn.in_proj_weight, clip.visual.transformer.resblocks.8.attn.in_proj_bias, clip.visual.transformer.resblocks.8.attn.out_proj.weight, clip.visual.transformer.resblocks.8.attn.out_proj.bias, clip.visual.transformer.resblocks.8.ln_1.weight, clip.visual.transformer.resblocks.8.ln_1.bias, clip.visual.transformer.resblocks.8.mlp.c_fc.weight, clip.visual.transformer.resblocks.8.mlp.c_fc.bias, clip.visual.transformer.resblocks.8.mlp.c_proj.weight, clip.visual.transformer.resblocks.8.mlp.c_proj.bias, clip.visual.transformer.resblocks.8.ln_2.weight, clip.visual.transformer.resblocks.8.ln_2.bias, clip.visual.transformer.resblocks.9.attn.in_proj_weight, clip.visual.transformer.resblocks.9.attn.in_proj_bias, clip.visual.transformer.resblocks.9.attn.out_proj.weight, clip.visual.transformer.resblocks.9.attn.out_proj.bias, clip.visual.transformer.resblocks.9.ln_1.weight, clip.visual.transformer.resblocks.9.ln_1.bias, clip.visual.transformer.resblocks.9.mlp.c_fc.weight, clip.visual.transformer.resblocks.9.mlp.c_fc.bias, clip.visual.transformer.resblocks.9.mlp.c_proj.weight, clip.visual.transformer.resblocks.9.mlp.c_proj.bias, clip.visual.transformer.resblocks.9.ln_2.weight, clip.visual.transformer.resblocks.9.ln_2.bias, clip.visual.transformer.resblocks.10.attn.in_proj_weight, clip.visual.transformer.resblocks.10.attn.in_proj_bias, clip.visual.transformer.resblocks.10.attn.out_proj.weight, clip.visual.transformer.resblocks.10.attn.out_proj.bias, clip.visual.transformer.resblocks.10.ln_1.weight, clip.visual.transformer.resblocks.10.ln_1.bias, clip.visual.transformer.resblocks.10.mlp.c_fc.weight, clip.visual.transformer.resblocks.10.mlp.c_fc.bias, clip.visual.transformer.resblocks.10.mlp.c_proj.weight, clip.visual.transformer.resblocks.10.mlp.c_proj.bias, clip.visual.transformer.resblocks.10.ln_2.weight, clip.visual.transformer.resblocks.10.ln_2.bias, clip.visual.transformer.resblocks.11.attn.in_proj_weight, clip.visual.transformer.resblocks.11.attn.in_proj_bias, clip.visual.transformer.resblocks.11.attn.out_proj.weight, clip.visual.transformer.resblocks.11.attn.out_proj.bias, clip.visual.transformer.resblocks.11.ln_1.weight, clip.visual.transformer.resblocks.11.ln_1.bias, clip.visual.transformer.resblocks.11.mlp.c_fc.weight, clip.visual.transformer.resblocks.11.mlp.c_fc.bias, clip.visual.transformer.resblocks.11.mlp.c_proj.weight, clip.visual.transformer.resblocks.11.mlp.c_proj.bias, clip.visual.transformer.resblocks.11.ln_2.weight, clip.visual.transformer.resblocks.11.ln_2.bias, clip.visual.ln_post.weight, clip.visual.ln_post.bias, clip.transformer.resblocks.0.attn.in_proj_weight, clip.transformer.resblocks.0.attn.in_proj_bias, clip.transformer.resblocks.0.attn.out_proj.weight, clip.transformer.resblocks.0.attn.out_proj.bias, clip.transformer.resblocks.0.ln_1.weight, clip.transformer.resblocks.0.ln_1.bias, clip.transformer.resblocks.0.mlp.c_fc.weight, clip.transformer.resblocks.0.mlp.c_fc.bias, clip.transformer.resblocks.0.mlp.c_proj.weight, clip.transformer.resblocks.0.mlp.c_proj.bias, clip.transformer.resblocks.0.ln_2.weight, clip.transformer.resblocks.0.ln_2.bias, clip.transformer.resblocks.1.attn.in_proj_weight, clip.transformer.resblocks.1.attn.in_proj_bias, clip.transformer.resblocks.1.attn.out_proj.weight, clip.transformer.resblocks.1.attn.out_proj.bias, clip.transformer.resblocks.1.ln_1.weight, clip.transformer.resblocks.1.ln_1.bias, clip.transformer.resblocks.1.mlp.c_fc.weight, clip.transformer.resblocks.1.mlp.c_fc.bias, clip.transformer.resblocks.1.mlp.c_proj.weight, clip.transformer.resblocks.1.mlp.c_proj.bias, clip.transformer.resblocks.1.ln_2.weight, clip.transformer.resblocks.1.ln_2.bias, clip.transformer.resblocks.2.attn.in_proj_weight, clip.transformer.resblocks.2.attn.in_proj_bias, clip.transformer.resblocks.2.attn.out_proj.weight, clip.transformer.resblocks.2.attn.out_proj.bias, clip.transformer.resblocks.2.ln_1.weight, clip.transformer.resblocks.2.ln_1.bias, clip.transformer.resblocks.2.mlp.c_fc.weight, clip.transformer.resblocks.2.mlp.c_fc.bias, clip.transformer.resblocks.2.mlp.c_proj.weight, clip.transformer.resblocks.2.mlp.c_proj.bias, clip.transformer.resblocks.2.ln_2.weight, clip.transformer.resblocks.2.ln_2.bias, clip.transformer.resblocks.3.attn.in_proj_weight, clip.transformer.resblocks.3.attn.in_proj_bias, clip.transformer.resblocks.3.attn.out_proj.weight, clip.transformer.resblocks.3.attn.out_proj.bias, clip.transformer.resblocks.3.ln_1.weight, clip.transformer.resblocks.3.ln_1.bias, clip.transformer.resblocks.3.mlp.c_fc.weight, clip.transformer.resblocks.3.mlp.c_fc.bias, clip.transformer.resblocks.3.mlp.c_proj.weight, clip.transformer.resblocks.3.mlp.c_proj.bias, clip.transformer.resblocks.3.ln_2.weight, clip.transformer.resblocks.3.ln_2.bias, clip.transformer.resblocks.4.attn.in_proj_weight, clip.transformer.resblocks.4.attn.in_proj_bias, clip.transformer.resblocks.4.attn.out_proj.weight, clip.transformer.resblocks.4.attn.out_proj.bias, clip.transformer.resblocks.4.ln_1.weight, clip.transformer.resblocks.4.ln_1.bias, clip.transformer.resblocks.4.mlp.c_fc.weight, clip.transformer.resblocks.4.mlp.c_fc.bias, clip.transformer.resblocks.4.mlp.c_proj.weight, clip.transformer.resblocks.4.mlp.c_proj.bias, clip.transformer.resblocks.4.ln_2.weight, clip.transformer.resblocks.4.ln_2.bias, clip.transformer.resblocks.5.attn.in_proj_weight, clip.transformer.resblocks.5.attn.in_proj_bias, clip.transformer.resblocks.5.attn.out_proj.weight, clip.transformer.resblocks.5.attn.out_proj.bias, clip.transformer.resblocks.5.ln_1.weight, clip.transformer.resblocks.5.ln_1.bias, clip.transformer.resblocks.5.mlp.c_fc.weight, clip.transformer.resblocks.5.mlp.c_fc.bias, clip.transformer.resblocks.5.mlp.c_proj.weight, clip.transformer.resblocks.5.mlp.c_proj.bias, clip.transformer.resblocks.5.ln_2.weight, clip.transformer.resblocks.5.ln_2.bias, clip.transformer.resblocks.6.attn.in_proj_weight, clip.transformer.resblocks.6.attn.in_proj_bias, clip.transformer.resblocks.6.attn.out_proj.weight, clip.transformer.resblocks.6.attn.out_proj.bias, clip.transformer.resblocks.6.ln_1.weight, clip.transformer.resblocks.6.ln_1.bias, clip.transformer.resblocks.6.mlp.c_fc.weight, clip.transformer.resblocks.6.mlp.c_fc.bias, clip.transformer.resblocks.6.mlp.c_proj.weight, clip.transformer.resblocks.6.mlp.c_proj.bias, clip.transformer.resblocks.6.ln_2.weight, clip.transformer.resblocks.6.ln_2.bias, clip.transformer.resblocks.7.attn.in_proj_weight, clip.transformer.resblocks.7.attn.in_proj_bias, clip.transformer.resblocks.7.attn.out_proj.weight, clip.transformer.resblocks.7.attn.out_proj.bias, clip.transformer.resblocks.7.ln_1.weight, clip.transformer.resblocks.7.ln_1.bias, clip.transformer.resblocks.7.mlp.c_fc.weight, clip.transformer.resblocks.7.mlp.c_fc.bias, clip.transformer.resblocks.7.mlp.c_proj.weight, clip.transformer.resblocks.7.mlp.c_proj.bias, clip.transformer.resblocks.7.ln_2.weight, clip.transformer.resblocks.7.ln_2.bias, clip.transformer.resblocks.8.attn.in_proj_weight, clip.transformer.resblocks.8.attn.in_proj_bias, clip.transformer.resblocks.8.attn.out_proj.weight, clip.transformer.resblocks.8.attn.out_proj.bias, clip.transformer.resblocks.8.ln_1.weight, clip.transformer.resblocks.8.ln_1.bias, clip.transformer.resblocks.8.mlp.c_fc.weight, clip.transformer.resblocks.8.mlp.c_fc.bias, clip.transformer.resblocks.8.mlp.c_proj.weight, clip.transformer.resblocks.8.mlp.c_proj.bias, clip.transformer.resblocks.8.ln_2.weight, clip.transformer.resblocks.8.ln_2.bias, clip.transformer.resblocks.9.attn.in_proj_weight, clip.transformer.resblocks.9.attn.in_proj_bias, clip.transformer.resblocks.9.attn.out_proj.weight, clip.transformer.resblocks.9.attn.out_proj.bias, clip.transformer.resblocks.9.ln_1.weight, clip.transformer.resblocks.9.ln_1.bias, clip.transformer.resblocks.9.mlp.c_fc.weight, clip.transformer.resblocks.9.mlp.c_fc.bias, clip.transformer.resblocks.9.mlp.c_proj.weight, clip.transformer.resblocks.9.mlp.c_proj.bias, clip.transformer.resblocks.9.ln_2.weight, clip.transformer.resblocks.9.ln_2.bias, clip.transformer.resblocks.10.attn.in_proj_weight, clip.transformer.resblocks.10.attn.in_proj_bias, clip.transformer.resblocks.10.attn.out_proj.weight, clip.transformer.resblocks.10.attn.out_proj.bias, clip.transformer.resblocks.10.ln_1.weight, clip.transformer.resblocks.10.ln_1.bias, clip.transformer.resblocks.10.mlp.c_fc.weight, clip.transformer.resblocks.10.mlp.c_fc.bias, clip.transformer.resblocks.10.mlp.c_proj.weight, clip.transformer.resblocks.10.mlp.c_proj.bias, clip.transformer.resblocks.10.ln_2.weight, clip.transformer.resblocks.10.ln_2.bias, clip.transformer.resblocks.11.attn.in_proj_weight, clip.transformer.resblocks.11.attn.in_proj_bias, clip.transformer.resblocks.11.attn.out_proj.weight, clip.transformer.resblocks.11.attn.out_proj.bias, clip.transformer.resblocks.11.ln_1.weight, clip.transformer.resblocks.11.ln_1.bias, clip.transformer.resblocks.11.mlp.c_fc.weight, clip.transformer.resblocks.11.mlp.c_fc.bias, clip.transformer.resblocks.11.mlp.c_proj.weight, clip.transformer.resblocks.11.mlp.c_proj.bias, clip.transformer.resblocks.11.ln_2.weight, clip.transformer.resblocks.11.ln_2.bias, clip.token_embedding.weight, clip.ln_final.weight, clip.ln_final.bias

**Comment by yeliudev** [comment]
Hi @ffiioonnaa! This should be normal. The weights for CLIP have already been loaded during initialization.
