### ISSUE TITLE
Question about the inference demo.

### ISSUE THREAD

**Issue by zefanZhang-cn** [yeliudev/R2-Tuning#8]
Thanks for your fantastic research. When I try to infer my video data, I find that the predicted output contains negative numbers. Why is this?
![image](https://github.com/yeliudev/R2-Tuning/assets/63379911/f1456dd1-1f9c-40cc-b278-c247b0a2e31a)

**Comment by yeliudev** [comment]
This is reasonable as we do not clamp the outputs. Sometimes the regressed boundaries are out of the video. I've updated the code to fix it.
